cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
restart-times: "0"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "5"
local-cores: 1
latency-wait: "3"
use-conda: "True"
use-singularity: "False"
jobs: "40"
printshellcmds: "True"
keep-going: "True"
rerun-incomplete: "True"
